version: '3'
services:
  postgres:
    image: postgres:10.5
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  wordpress:
    image: ntninja/wordpress-postgresql:latest 
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: postgres
      WORDPRESS_DB_NAME: postgres
      WORDPRESS_DB_USER: postgres
      WORDPRESS_DB_PASSWORD: postgres
    volumes:
      - wordpress:/var/www/html 
    networks:
      - app-network
    depends_on:
      - postgres

  app:
    build: ./python 
    container_name: app
    restart: always
    env_file:
      - .env
    command:
      gunicorn --workers=2 --bind=0.0.0.0:8000 mysite.wsgi:application
    networks:
      - app-network

  node:
    image: node:16.13.2-alpine3.15
    container_name: node
    working_dir: /opt/server 
    volumes:
      - ./node:/opt/server 
    command: node test.js 
    networks:
      - app-network

  nginx:
    image: nginx:1.15.12-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8083:8083
      - 8081:8081
      - 8082:8082
    volumes:
      - wordpress:/var/www/html  # изменено с ./wordpress на именованный том
      - ./nginx-conf:/etc/nginx/conf.d 
    networks:
      - app-network
    depends_on: 
      - wordpress
      - app
      - node

volumes:
  wordpress:   # добавлено объявление именованного тома
  dbdata:

networks:
  app-network:
    driver: bridge
